@echo off
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scriptsctivate
echo Installing dependencies...
pip install -r requirements_full.txt
echo Running application...
python main.py
pause